### PR TITLE
Set the license to the ISC license

### PR DESCRIPTION
**Pull request by ExE-Boss**
The ISC license was chosen as it’s the license under which the <code>${[hyper](https://github.com/WebReflection/hyperHTML/blob/master/LICENSE.txt),[viper](https://github.com/WebReflection/viperHTML/blob/master/LICENSE.txt),[basic](https://github.com/WebReflection/basicHTML/blob/master/LICENSE.txt),[native](https://github.com/WebReflection/nativeHTML/blob/master/README.md)}⁠[HTML</code> family](https://viperhtml.js.org) is published.

As with any project which wants to change the license, I need agreement from all past contributors to this repository:
- [x] @alexandre-mouton-brady
- [x] @albertosantini
- [x] @gabrox999
- [x] @grommett
- [x] @joshgillies
- [x] @sourcegr
- [x] @synaptiko
- [x] @viperHTML (also see #18)
- [x] @WebReflection

### CODE REVIEW

**Comment by WebReflection** [comment]
please rename LICENSE.txt to LICENSE so GitHub is also happy, thanks.

btw, this is the website, not the library.

**Comment by ExE-Boss** [comment]
> btw, this is the website, not the library.

I am well aware.

**Comment by synaptiko** [comment]
consent granted

**Comment by gabrox999** [comment]
consent granted

**Comment by albertosantini** [comment]
consent granted

**Comment by grommett** [comment]
consent granted

**Comment by WebReflection** [comment]
@joshgillies and @alexandre-mouton-brady please tell us you are OK with setting ISC license in here, thanks

**Comment by joshgillies** [comment]
@WebReflection thanks for the nudge! I'm +1 for this also

**Comment by alexandre-mouton-brady** [comment]
consent granted

**Pull request merged**
